;;; 加载使用第三方服务所需要的密钥
(load-file "~/Documents/Configs/emacs/dict.el")

(defun lt-load-config (path)
  "加载特定目录下的PATH配置文件"
  (load-file (concat "~/Projects/Configurations/emacs/" path)))

(lt-load-config "core/appearance.el")
(lt-load-config "core/behavior.el")
(lt-load-config "core/key.el")
(lt-load-config "core/modes/c.el")
(lt-load-config "core/modes/org.el")
(lt-load-config "core/modes/sdedit.el")
(lt-load-config "core/udf.el")
(lt-load-config "packages/melpa.el")
;; (lt-load-config "packages/auto-complete.el")
(lt-load-config "packages/avy.el")
(lt-load-config "packages/company.el")
(lt-load-config "packages/company-quickhelp.el")
(lt-load-config "packages/dashboard.el")
(lt-load-config "packages/dimmer.el")
;; (lt-load-config "packages/eglot.el")
(lt-load-config "packages/flycheck.el")
(lt-load-config "packages/helm-swoop.el")
(lt-load-config "packages/helm.el")
;;; 试一下将dumb-jump放到helm之后来解决Invalid function: helm-build-sync-source的问题
;; (lt-load-config "packages/dumb-jump.el")
(lt-load-config "packages/idle-highlight.el")
(lt-load-config "packages/ido.el")
(lt-load-config "packages/js-mode.el")
(lt-load-config "packages/js2-mode.el")
(lt-load-config "packages/ledger.el")
(lt-load-config "packages/magit.el")
(lt-load-config "packages/markdown.el")
(lt-load-config "packages/org.el")
(lt-load-config "~/Projects/cuckoo/contrib/emacs/org-cuckoo.el")
(lt-load-config "packages/org-edna.el")
(lt-load-config "packages/paredit.el")
(lt-load-config "packages/powerline.el")
(lt-load-config "packages/projectile.el")
(lt-load-config "packages/protocolbuffer.el")
(lt-load-config "packages/racer.el")
(lt-load-config "packages/restclient.el")
(lt-load-config "packages/slime.el")
(lt-load-config "packages/smex.el")
(lt-load-config "packages/swiper.el")
;; (lt-load-config "packages/swiper-helm.el")
(lt-load-config "packages/switch-window.el")
(load-theme 'gruvbox-dark-medium t)
(lt-load-config "packages/uuidgen.el")
(lt-load-config "packages/wakatime.el")
(lt-load-config "packages/xref-js2.el")
(lt-load-config "packages/yasnippet.el")
