;;; 加载使用第三方服务所需要的密钥
(load-file "~/Documents/Configs/emacs/dict.el")

(load-file "~/Documents/Projects/EmacsSettings/core/appearance.el")
(load-file "~/Documents/Projects/EmacsSettings/core/behavior.el")
(load-file "~/Documents/Projects/EmacsSettings/core/key.el")
(load-file "~/Documents/Projects/EmacsSettings/core/modes/c.el")
(load-file "~/Documents/Projects/EmacsSettings/core/modes/org.el")
(load-file "~/Documents/Projects/EmacsSettings/core/modes/sdedit.el")
(load-file "~/Documents/Projects/EmacsSettings/core/udf.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/melpa.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/auto-complete.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/avy.el")
;; (load-file "~/Documents/Projects/EmacsSettings/packages/company.el")
;; (load-file "~/Documents/Projects/EmacsSettings/packages/company-quickhelp.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/dashboard.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/dimmer.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/dumb-jump.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/flycheck.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/helm-swoop.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/helm.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/idle-highlight.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/ido.el")
;; (load-file "~/Documents/Projects/EmacsSettings/packages/ivy.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/js-mode.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/magit.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/markdown.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/org.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/org-edna.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/paredit.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/powerline.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/projectile.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/protocolbuffer.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/racer.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/restclient.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/slime.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/smex.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/swiper.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/switch-window.el")
(load-file "~/Documents/Projects/EmacsSettings/packages/wakatime.el")
